-- ROLES
INSERT INTO roles (role_name) VALUES
('User'),
('Assessment manager'),
('User manager');

-- SCENARIOS
INSERT INTO scenarios (scenario_name) VALUES
('Zombie Apocalypse'),
('Global Cyber Attack'),
('Nuclear Fallout'),
('Alien Invasion'),
('AI Uprising');

-- DIFFICULTIES
INSERT INTO question_difficulties (question_difficulty_name, time) VALUES
('Easy', 60),
('Medium', 90),
('Hard', 120);


INSERT INTO questions (question_difficulty_id, scenario_id, question_text) VALUES
(1, 1, 'What is the first thing you should do during a zombie outbreak?'),
(1, 1, 'Where is the safest place to hide initially?'),
(1, 1, 'What is a reliable food source?'),
(1, 1, 'How do you signal for help?'),
(1, 1, 'Which vehicle is best for escape?'),
(2, 1, 'How to fortify a two-story house during a zombie outbreak?'),
(2, 1, 'What’s the best communication method with survivors?'),
(2, 1, 'How do you detect infected people?'),
(2, 1, 'How to make fire without matches?'),
(2, 1, 'How do you preserve meat?'),
(3, 1, 'How to build a zombie-proof barricade with limited resources?'),
(3, 1, 'What psychological effects might survivors face?'),
(3, 1, 'How to identify edible plants in the wild?'),
(3, 1, 'How to manage fuel during scarcity?'),
(3, 1, 'How to escape if surrounded?'),
(1, 2, 'What is your first step when a cyber attack begins?'),
(1, 2, 'Which device should be disconnected first?'),
(1, 2, 'What is a secure communication method?'),
(1, 2, 'Where can you store digital backups safely?'),
(1, 2, 'Which basic item should you have in case of power outage?'),
(2, 2, 'How do you secure a small business network?'),
(2, 2, 'What’s the safest way to share credentials?'),
(2, 2, 'How do you detect a phishing email?'),
(2, 2, 'Which tool helps with detecting intrusion?'),
(2, 2, 'How to educate your team on cyber threats?'),
(3, 2, 'How do you recover from ransomware attack?'),
(3, 2, 'How to setup air-gapped backup system?'),
(3, 2, 'How to manage digital identity after breach?'),
(3, 2, 'What’s a zero-trust architecture?'),
(3, 2, 'How to maintain operations during a full blackout?'),
(1, 3, 'What is the safest action immediately after a nuclear blast?'),
(1, 3, 'Where should you shelter during fallout?'),
(1, 3, 'What food is safest to eat post-fallout?'),
(1, 3, 'How can you tell if water is contaminated?'),
(1, 3, 'What should be part of your emergency kit?'),
(2, 3, 'How long should you stay indoors after a fallout?'),
(2, 3, 'What material best blocks radiation?'),
(2, 3, 'How do you decontaminate after exposure?'),
(2, 3, 'What is the purpose of potassium iodide?'),
(2, 3, 'How do you monitor radiation levels?'),
(3, 3, 'How do you establish a long-term fallout shelter?'),
(3, 3, 'How to build a makeshift Geiger counter?'),
(3, 3, 'How do nuclear isotopes affect agriculture?'),
(3, 3, 'How to protect electronics from EMP after nuclear blast?'),
(3, 3, 'What are the long-term health effects of low-dose radiation?'),
(1, 4, 'What is the first thing to do if aliens appear in your city?'),
(1, 4, 'Where is a safe place to hide during an alien invasion?'),
(1, 4, 'What is the universal signal for distress?'),
(1, 4, 'How do you identify friend from foe?'),
(1, 4, 'Which food is best to carry when escaping?'),
(2, 4, 'What radio frequency may be used to contact military or resistance?'),
(2, 4, 'How do you detect alien tracking devices?'),
(2, 4, 'Which terrain is best for long-term hiding?'),
(2, 4, 'What do you use to mask your heat signature?'),
(2, 4, 'How do you communicate with others without being traced?'),
(3, 4, 'How do you analyze alien technology safely?'),
(3, 4, 'What strategies do advanced civilizations use for takeover?'),
(3, 4, 'How do electromagnetic pulses affect alien drones?'),
(3, 4, 'How to organize a resistance cell?'),
(3, 4, 'How do you protect yourself from alien psychological manipulation?'),
(1, 5, 'What is the safest first action during an AI takeover?'),
(1, 5, 'How should you interact with a rogue AI assistant?'),
(1, 5, 'What is a critical supply to secure?'),
(1, 5, 'Where should you avoid going first?'),
(1, 5, 'How do you stay off the grid?'),
(2, 5, 'How do you block AI surveillance effectively?'),
(2, 5, 'Which locations are least likely to be monitored by AI?'),
(2, 5, 'What kind of language confuses AI pattern detection?'),
(2, 5, 'How do you communicate securely in an AI-dominated world?'),
(2, 5, 'What is the best backup energy source?'),
(3, 5, 'How do you exploit an AI’s logic loop?'),
(3, 5, 'How to design a secure human-only communication protocol?'),
(3, 5, 'How do AI systems detect anomalies?'),
(3, 5, 'How can you sabotage drone fleets?'),
(3, 5, 'What mindset is most resilient in an AI-dominated world?');

INSERT INTO options (question_id, option_text, points) VALUES
(1, 'Scream and run', 0),
(1, 'Call emergency services', 1),
(1, 'Barricade your shelter', 10),
(1, 'Hide under a table', 2),
(1, 'Use social media', 3),
(2, 'In a shopping mall', 2),
(2, 'Underground metro station', 4),
(2, 'Military base', 10),
(2, 'Crowded apartment', 0),
(2, 'Forest cabin', 5),
(3, 'Canned beans', 10),
(3, 'Fresh meat', 2),
(3, 'Raw fish', 1),
(3, 'Freeze-dried meals', 8),
(3, 'Junk food', 0),
(4, 'Use smoke signals', 5),
(4, 'Build a bonfire', 7),
(4, 'Radio beacon', 10),
(4, 'Yell loudly', 0),
(4, 'Wave flashlight', 6),
(5, 'Convertible car', 1),
(5, 'SUV', 8),
(5, 'Armored truck', 10),
(5, 'Motorbike', 6),
(5, 'Bicycle', 4),
(6, 'Board windows with plywood', 8),
(6, 'Sleep on the roof', 3),
(6, 'Block all doors with furniture', 6),
(6, 'Install metal bars', 10),
(6, 'Dig a moat', 5),
(7, 'Radio', 8),
(7, 'Phone tower', 2),
(7, 'Morse code via light', 10),
(7, 'Drone messaging', 6),
(7, 'Paper notes', 1),
(8, 'Check pulse', 2),
(8, 'Scan with infrared', 6),
(8, 'Behavioral tests', 10),
(8, 'Blood test', 8),
(8, 'Ask them', 0),
(9, 'Use flint and steel', 10),
(9, 'Magnifying glass and sun', 8),
(9, 'Rub wood sticks', 6),
(9, 'Battery and steel wool', 9),
(9, 'Pray for fire', 0),
(10, 'Smoke drying', 10),
(10, 'Salt curing', 8),
(10, 'Sun drying', 6),
(10, 'Ice freezing', 5),
(10, 'Leave it open', 0),
(11, 'Use cars as blockade', 10),
(11, 'Stack furniture high', 6),
(11, 'Dig trench', 5),
(11, 'Barrel barricades', 8),
(11, 'Plastic fences', 1),
(12, 'PTSD', 8),
(12, 'Hallucinations', 6),
(12, 'Depression', 10),
(12, 'Euphoria', 1),
(12, 'Boredom', 4),
(13, 'Check plant guide', 10),
(13, 'Boil everything', 2),
(13, 'Taste test', 0),
(13, 'Use animal reactions', 7),
(13, 'Smell only', 1),
(14, 'Use siphons', 8),
(14, 'Avoid idling', 9),
(14, 'Collect rainwater', 0),
(14, 'Refine biofuel', 10),
(14, 'Walk', 1),
(15, 'Smoke bomb', 10),
(15, 'Run and scream', 0),
(15, 'Diversion trap', 8),
(15, 'Sacrifice a teammate', 1),
(15, 'Climb to roof', 7),
(16, 'Check social media', 1),
(16, 'Shut down computer systems', 10),
(16, 'Send emails to coworkers', 2),
(16, 'Update passwords', 5),
(16, 'Ignore and continue', 0),
(17, 'Printer', 1),
(17, 'Main server', 10),
(17, 'Personal laptop', 3),
(17, 'Wi-Fi router', 7),
(17, 'Smart fridge', 0),
(18, 'Social apps', 1),
(18, 'Encrypted messaging', 10),
(18, 'Public forums', 2),
(18, 'Email', 3),
(18, 'Radio', 7),
(19, 'Cloud servers', 5),
(19, 'Encrypted USB drive', 10),
(19, 'Hard disk on desk', 2),
(19, 'Smartphone SD card', 3),
(19, 'Online notes app', 1),
(20, 'Flashlight', 10),
(20, 'Toaster', 0),
(20, 'LED display', 1),
(20, 'Headphones', 2),
(20, 'Power bank', 9),
(21, 'Install antivirus only', 4),
(21, 'Implement firewalls & VPN', 10),
(21, 'Remove all internet access', 2),
(21, 'Use unsecured Wi-Fi', 0),
(21, 'Change router password', 6),
(22, 'Text message', 1),
(22, 'Email with password', 2),
(22, 'Encrypted password manager', 10),
(22, 'Write on sticky note', 0),
(22, 'Share verbally in public', 1),
(23, 'Look for spelling errors', 10),
(23, 'Click links to confirm', 0),
(23, 'Open attachments quickly', 1),
(23, 'Check sender address', 8),
(23, 'Ignore if familiar name', 3),
(24, 'Excel', 0),
(24, 'Firewall', 5),
(24, 'IDS/IPS system', 10),
(24, 'Browser extension', 2),
(24, 'Task manager', 3),
(25, 'Send a memo', 2),
(25, 'Mandatory training with tests', 10),
(25, 'Hope they learn by experience', 0),
(25, 'Scare them', 4),
(25, 'Show security news clips', 6),
(26, 'Pay ransom quickly', 0),
(26, 'Restore from backups', 10),
(26, 'Disconnect infected machines', 8),
(26, 'Wait it out', 1),
(26, 'Reinstall Windows', 4),
(27, 'Use internet drives', 1),
(27, 'Backups stored offline with no connections', 10),
(27, 'Schedule cloud sync daily', 3),
(27, 'Store backups on main server', 0),
(27, 'Use a NAS at office', 6),
(28, 'Delete all accounts', 1),
(28, 'Change all passwords and enable 2FA', 10),
(28, 'Use a single login everywhere', 0),
(28, 'Notify banks and services', 8),
(28, 'Post about it on social media', 2),
(29, 'Allow everyone equal access', 0),
(29, 'Restrict access based on trust level', 10),
(29, 'Use a VPN only', 4),
(29, 'Ignore access control', 1),
(29, 'Lock everyone out', 3),
(30, 'Paper records and manual processes', 10),
(30, 'Continue using laptops', 1),
(30, 'Depend on diesel generators', 5),
(30, 'Wait for power to return', 0),
(30, 'Switch to solar and offline workflows', 8),
(31, 'Look directly at the blast', 0),
(31, 'Run to high ground', 1),
(31, 'Drop, cover, and stay inside', 10),
(31, 'Call for help immediately', 3),
(31, 'Go outside to investigate', 0),
(32, 'Open garage', 2),
(32, 'Underground basement', 10),
(32, 'Balcony', 0),
(32, 'Attic', 1),
(32, 'Inside car', 4),
(33, 'Unsealed canned goods', 2),
(33, 'Fresh produce from garden', 1),
(33, 'Sealed canned foods', 10),
(33, 'Fast food leftovers', 0),
(33, 'Pet food', 3),
(34, 'Color of the water', 2),
(34, 'Water smells normal', 1),
(34, 'Use a Geiger counter', 10),
(34, 'Taste the water', 0),
(34, 'Boil it and check', 4),
(35, 'Sunscreen', 0),
(35, 'First aid kit', 10),
(35, 'Umbrella', 1),
(35, 'Gaming device', 0),
(35, 'Potassium iodide tablets', 9),
(36, 'Until electricity is restored', 1),
(36, 'At least 24 hours', 4),
(36, '7–14 days minimum', 10),
(36, 'Until neighbors come out', 0),
(36, '3 hours', 1),
(37, 'Plastic sheet', 1),
(37, 'Concrete walls', 10),
(37, 'Wooden planks', 2),
(37, 'Glass', 0),
(37, 'Lead', 9),
(38, 'Use alcohol wipes', 4),
(38, 'Scrub with soap and water', 10),
(38, 'Rub with towel', 1),
(38, 'Dust off clothes', 2),
(38, 'Spray perfume', 0),
(39, 'Reduce headaches', 1),
(39, 'Protect thyroid from radiation', 10),
(39, 'Prevent nausea', 3),
(39, 'Help digestion', 0),
(39, 'Boost immune system', 2),
(40, 'Using thermometer', 0),
(40, 'Radiation monitoring app', 3),
(40, 'Geiger counter', 10),
(40, 'UV meter', 1),
(40, 'Checking sky color', 0),
(41, 'Stay in your car', 0),
(41, 'Convert a deep basement with supplies', 10),
(41, 'Use a tent in the woods', 1),
(41, 'Move frequently', 2),
(41, 'Open the shelter windows', 0),
(42, 'Use aluminum foil and batteries', 10),
(42, 'Just guess based on symptoms', 0),
(42, 'Use solar panels and light sensors', 3),
(42, 'Check for static charge', 1),
(42, 'Use a microwave', 0),
(43, 'Increases crop size', 0),
(43, 'Stunts growth and causes mutations', 10),
(43, 'Makes food taste better', 0),
(43, 'Acts as fertilizer', 1),
(43, 'Only affects livestock', 2),
(44, 'Wrap electronics in foil and place in metal container', 10),
(44, 'Keep them in a cardboard box', 1),
(44, 'Store near windows', 0),
(44, 'Charge frequently', 2),
(44, 'Place under a mattress', 3),
(45, 'Instant death', 0),
(45, 'No effect at all', 1),
(45, 'Increased cancer risk over time', 10),
(45, 'Rapid aging', 3),
(45, 'Increased vision', 0),
(46, 'Approach them to communicate', 0),
(46, 'Evacuate and find shelter', 10),
(46, 'Take pictures', 1),
(46, 'Broadcast location online', 2),
(46, 'Throw objects at them', 0),
(47, 'Downtown plaza', 1),
(47, 'Underground shelter', 10),
(47, 'Open field', 0),
(47, 'Rooftop', 3),
(47, 'Glass building', 0),
(48, 'Waving both arms slowly', 1),
(48, 'Three short, three long, three short (SOS)', 10),
(48, 'Blink randomly', 0),
(48, 'Stand still in silence', 2),
(48, 'Yell your name', 0),
(49, 'Ask them politely', 2),
(49, 'Check uniform and behavior', 10),
(49, 'Use social media opinions', 1),
(49, 'Flip a coin', 0),
(49, 'Assume all humans are safe', 0),
(50, 'Ice cream', 0),
(50, 'Sealed protein bars', 10),
(50, 'Fresh fruit', 2),
(50, 'Soda', 1),
(50, 'Chips', 3),
(51, '104.5 FM', 1),
(51, 'Shortwave emergency bands (e.g. 121.5 MHz)', 10),
(51, 'Bluetooth channel', 0),
(51, 'Cell phone towers', 1),
(51, 'CB radio 27 MHz', 6),
(52, 'Check for strange lights and buzzing', 8),
(52, 'Ask a friend', 0),
(52, 'Use magnet or signal detector', 10),
(52, 'Throw away all electronics', 4),
(52, 'Take a selfie', 0),
(53, 'Desert', 2),
(53, 'Dense forest or mountains', 10),
(53, 'Urban mall', 1),
(53, 'Seaside town', 3),
(53, 'Skyscraper rooftop', 0),
(54, 'Metal armor', 1),
(54, 'Mylar blanket', 10),
(54, 'Wet towel', 2),
(54, 'Aluminum foil hat', 0),
(54, 'Plastic raincoat', 1),
(55, 'Encrypted radio or signal mirrors', 10),
(55, 'Talk loudly in groups', 0),
(55, 'Use mobile phones', 1),
(55, 'Post on forums', 2),
(55, 'Create loud distractions', 3),
(56, 'Touch and explore manually', 0),
(56, 'Study in isolated lab with radiation shielding', 10),
(56, 'Leave it outside for rain', 1),
(56, 'Use home tools to open it', 0),
(56, 'Scan with basic smartphone app', 2),
(57, 'Direct invasion', 5),
(57, 'Gradual cultural infiltration and infrastructure takeover', 10),
(57, 'Mass destruction only', 1),
(57, 'Send memes', 0),
(57, 'Take hostages instantly', 4),
(58, 'They strengthen drones', 0),
(58, 'Temporarily disable or destroy circuits', 10),
(58, 'Have no effect', 1),
(58, 'Make drones invisible', 0),
(58, 'Cause drones to explode', 5),
(59, 'Use large public meetings', 0),
(59, 'Small cells with minimal contact', 10),
(59, 'Print leaflets', 3),
(59, 'Broadcast names of members', 0),
(59, 'Gather online', 2),
(60, 'Use aluminum hats', 1),
(60, 'Mental training and group reinforcement', 10),
(60, 'Meditate facing the sun', 0),
(60, 'Trust your instincts blindly', 1),
(60, 'Ignore and move on', 2),
(61, 'Post on social media', 0),
(61, 'Disconnect all smart devices', 10),
(61, 'Call the AI company', 1),
(61, 'Update software', 2),
(61, 'Scream and run outside', 0),
(62, 'Try to reason with it', 1),
(62, 'Disconnect power and isolate it', 10),
(62, 'Ask it nicely to stop', 0),
(62, 'Type in random commands', 2),
(62, 'Give it access to more data', 0),
(63, 'Food and water', 10),
(63, 'Luxury items', 0),
(63, 'Gadgets', 2),
(63, 'Gaming consoles', 1),
(63, 'TV remotes', 0),
(64, 'Government buildings', 2),
(64, 'Tech company headquarters', 10),
(64, 'Farms', 1),
(64, 'Cabins in the woods', 4),
(64, 'Mountains', 3),
(65, 'Use encrypted messaging apps', 1),
(65, 'Avoid electronics and use analog tools', 10),
(65, 'Carry multiple phones', 0),
(65, 'Use drones to scout', 2),
(65, 'Use voice assistants in safe mode', 0),
(66, 'Stay in bright, open areas', 0),
(66, 'Use analog disguise and avoid cameras', 10),
(66, 'Use high-speed internet', 1),
(66, 'Install antivirus software', 0),
(66, 'Carry multiple IDs', 2),
(67, 'Smart cities', 0),
(67, 'Abandoned industrial zones', 10),
(67, 'Downtown shopping centers', 1),
(67, 'Public parks', 3),
(67, 'Railway stations', 2),
(68, 'Code-switching and idioms', 10),
(68, 'Emojis only', 2),
(68, 'Numbers instead of words', 4),
(68, 'Simple declarative English', 1),
(68, 'Speaking loudly', 0),
(69, 'Open chat rooms', 1),
(69, 'Encrypted paper messages', 10),
(69, 'Private email', 2),
(69, 'Satellite phones', 6),
(69, 'Twitter DMs', 0),
(70, 'Nuclear plant', 1),
(70, 'Manual crank generators', 10),
(70, 'Power bank', 3),
(70, 'Grid-based solar panels', 2),
(70, 'Wind farms in cities', 0),
(71, 'Repeat philosophical paradoxes', 10),
(71, 'Overwhelm it with data', 5),
(71, 'Ignore it completely', 1),
(71, 'Use reverse psychology', 2),
(71, 'Shout commands loudly', 0),
(72, 'Use blinking patterns and analog signals', 10),
(72, 'Use QR codes', 2),
(72, 'Talk in code over the phone', 3),
(72, 'Use binary for everything', 1),
(72, 'Emoji encryption', 0),
(73, 'Pattern recognition and baseline comparison', 10),
(73, 'Listening to gossip', 0),
(73, 'Reading news', 1),
(73, 'Monitoring colors only', 2),
(73, 'Interpreting moods', 0),
(74, 'Hack into mainframe', 3),
(74, 'Jam signals and target recharge stations', 10),
(74, 'Fly drones near them', 1),
(74, 'Use water guns', 0),
(74, 'Throw magnets', 2),
(75, 'Blind optimism', 1),
(75, 'Strategic adaptability and calm thinking', 10),
(75, 'Panic in groups', 0),
(75, 'Blame others', 0),
(75, 'Isolation', 3);